In [3]:
import numpy as np

# Matriks A
A = np.array([
    [10, -5, -4],
    [6, -5, -1],
    [-17, 10, 8]
], dtype=float)

# ======== Fungsi Minor ========
def minor_matrix(A, i, j):
    return np.delete(np.delete(A, i, axis=0), j, axis=1)

# ======== Fungsi Determinan (Cofactor Expansion) ========
def determinant(A):
    # kasus 2x2
    if A.shape == (2, 2):
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]

    det = 0
    for j in range(A.shape[1]):
        det += ((-1)**j) * A[0,j] * determinant(minor_matrix(A, 0, j))
    return det

# ======== Fungsi Cofactor Matrix ========
def cofactor_matrix(A):
    n = A.shape[0]
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = minor_matrix(A, i, j)
            C[i,j] = ((-1)**(i+j)) * determinant(minor)
    return C

# ======== Fungsi Adjoint ========
def adjoint(A):
    return cofactor_matrix(A).T

# ======== Fungsi Inverse Matrix ========
def inverse(A):
    detA = determinant(A)
    if detA == 0:
        raise ValueError("Matrix tidak memiliki invers (determinant = 0)")
    return adjoint(A) / detA


# =============== MAIN PROGRAM ==================

detA = determinant(A)
invA = inverse(A)

print("Matrix A:\n", A)
print("\nDeterminant = ", detA)
print("\nInverse matrix:\n", invA)

# Verifikasi dengan numpy
print("\n--- VERIFIKASI NUMPY ---")
print("numpy det:", np.linalg.det(A))
print("numpy inv:\n", np.linalg.inv(A))

Matrix A:
 [[ 10.  -5.  -4.]
 [  6.  -5.  -1.]
 [-17.  10.   8.]]

Determinant =  -45.0

Inverse matrix:
 [[ 0.66666667  0.          0.33333333]
 [ 0.68888889 -0.26666667  0.31111111]
 [ 0.55555556  0.33333333  0.44444444]]

--- VERIFIKASI NUMPY ---
numpy det: -45.000000000000036
numpy inv:
 [[ 6.66666667e-01 -7.83686841e-17  3.33333333e-01]
 [ 6.88888889e-01 -2.66666667e-01  3.11111111e-01]
 [ 5.55555556e-01  3.33333333e-01  4.44444444e-01]]


In [ ]:
import numpy as np

# ============================
# CLEAN OUTPUT
# ============================
def clean_matrix(M, decimal=6):
    M = np.round(M, decimal)           # bulatkan
    M[np.abs(M) < 1e-10] = 0           # ubah angka kecil jadi 0
    return M

# ============================
# FUNGSI MINOR
# ============================
def minor_matrix(A, i, j):
    return np.delete(np.delete(A, i, axis=0), j, axis=1)

# ============================
# DETERMINANT (COFACTOR EXPANSION)
# ============================
def determinant(A):
    if A.shape == (2, 2):
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]

    det = 0
    for j in range(A.shape[1]):
        det += ((-1)**j) * A[0,j] * determinant(minor_matrix(A, 0, j))
    return det

# ============================
# FUNGSI COFACTOR + PRINT LANGKAH
# ============================
def cofactor_matrix_verbose(A):
    n = A.shape[0]
    C = np.zeros((n, n))

    print("\n========================")
    print("   LANGKAH: MINOR & COFACTOR")
    print("========================\n")

    for i in range(n):
        for j in range(n):
            M = minor_matrix(A, i, j)
            C_ij = ((-1)**(i+j)) * determinant(M)

            print(f"Minor M[{i+1},{j+1}] (hapus baris {i+1}, kolom {j+1}):")
            print(clean_matrix(M))
            print(f"Cofactor C[{i+1},{j+1}] = (-1)^{i+j} * det(M)")
            print(f"               = {C_ij}\n")

            C[i,j] = C_ij

    print("Matriks Cofactor C:")
    print(clean_matrix(C))
    return C

# ============================
# ADJOINT
# ============================
def adjoint_verbose(A):
    C = cofactor_matrix_verbose(A)
    adj = C.T
    print("\n========================")
    print("         ADJOINT")
    print("========================\n")
    print(clean_matrix(adj))
    return adj

# ============================
# INVERSE
# ============================
def inverse_verbose(A):
    print("\n========================")
    print("       PERHITUNGAN INVERS")
    print("========================\n")

    detA = determinant(A)
    print(f"Determinant = {detA}\n")

    if abs(detA) < 1e-12:
        raise ValueError("Matriks tidak memiliki invers (det = 0)")

    adj = adjoint_verbose(A)
    inv = adj / detA

    print("\n========================")
    print("         INVERS")
    print("========================\n")
    print(clean_matrix(inv))

    return clean_matrix(inv)

# ======================================================
#                         MAIN
# ======================================================

# Hardcoded example matrix for demonstration
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
], dtype=float)

print("\nMatrix A:")
print(clean_matrix(A))

# Hitung invers
invA = inverse_verbose(A)

# ============================
# VERIFIKASI NUMPY
# ============================
print("\n========================")
print("     VERIFIKASI NUMPY")
print("========================\n")

print("numpy det =", np.linalg.det(A))
try:
    print("numpy inv:")
    print(clean_matrix(np.linalg.inv(A)))
except:
    print("numpy tidak bisa menghitung invers (det = 0)")


Matrix A:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

       PERHITUNGAN INVERS

Determinant = 1.0


   LANGKAH: MINOR & COFACTOR

Minor M[1,1] (hapus baris 1, kolom 1):
[[1. 4.]
 [6. 0.]]
Cofactor C[1,1] = (-1)^0 * det(M)
               = -24.0

Minor M[1,2] (hapus baris 1, kolom 2):
[[0. 4.]
 [5. 0.]]
Cofactor C[1,2] = (-1)^1 * det(M)
               = 20.0

Minor M[1,3] (hapus baris 1, kolom 3):
[[0. 1.]
 [5. 6.]]
Cofactor C[1,3] = (-1)^2 * det(M)
               = -5.0

Minor M[2,1] (hapus baris 2, kolom 1):
[[2. 3.]
 [6. 0.]]
Cofactor C[2,1] = (-1)^1 * det(M)
               = 18.0

Minor M[2,2] (hapus baris 2, kolom 2):
[[1. 3.]
 [5. 0.]]
Cofactor C[2,2] = (-1)^2 * det(M)
               = -15.0

Minor M[2,3] (hapus baris 2, kolom 3):
[[1. 2.]
 [5. 6.]]
Cofactor C[2,3] = (-1)^3 * det(M)
               = 4.0

Minor M[3,1] (hapus baris 3, kolom 1):
[[2. 3.]
 [1. 4.]]
Cofactor C[3,1] = (-1)^2 * det(M)
               = 5.0

Minor M[3,2] (hapus baris 3, kolom 2):
[[1. 3.]
 [0. 4.]]
Cofactor C[

In [ ]:
from fractions import Fraction
import re

# =============================
# Input baris dengan Fraction
# =============================
def input_baris(prompt):
    raw = input(prompt)
    raw = raw.replace(",", ".")   # 2,5 → 2.5
    return [Fraction(x) for x in raw.split()]

# =============================
# Determinan Rekursif (cofactor)
# =============================
def determinan(M):
    n = len(M)
    if n == 1:
        return M[0][0]
    if n == 2:
        return M[0][0]*M[1][1] - M[0][1]*M[1][0]

    det = Fraction(0)
    for j in range(n):
        minor = []
        for row in M[1:]:
            minor.append([row[k] for k in range(n) if k != j])
        det += ((-1)**j) * M[0][j] * determinan(minor)
    return det

# =============================
# Minor Matrix
# =============================
def minor_matrix(M, i, j):
    return [
        [M[r][c] for c in range(len(M)) if c != j]
        for r in range(len(M)) if r != i
    ]

# =============================
# Cofactor Matrix
# =============================
def matrix_cofactor(M):
    n = len(M)
    C = [[Fraction(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            C[i][j] = ((-1)**(i+j)) * determinan(minor_matrix(M, i, j))
    return C

# =============================
# Transpose
# =============================
def transpose(M):
    return [list(row) for row in zip(*M)]

# =============================
# Invers via Adjoin/Cofactor
# =============================
def inverse(M):
    detA = determinan(M)
    if detA == 0:
        raise ValueError("Matriks tidak memiliki invers (det = 0).")
    C = matrix_cofactor(M)
    adj = transpose(C)
    inv = [[adj[i][j] / detA for j in range(len(M))] for i in range(len(M))]
    return inv

# =============================
# Perkalian Matriks
# =============================
def multiply(A, B):
    n = len(A)
    R = [[Fraction(0) for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
            for k in range(n):
                R[i][j] += A[i][k] * B[k][j]
    return R

# =============================
# MAIN PROGRAM
# =============================
# Input ukuran
ukuran = input("Masukkan ukuran matriks (contoh: 3 atau 3x3): ")
angka = re.findall(r'\d+', ukuran)
n = int(angka[0])

# Input matriks
print(f"\nMasukkan elemen-elemen matriks {n}x{n}:")
A = []
for i in range(n):
    row = input_baris(f"Baris {i+1}: ")
    while len(row) != n:
        print("Jumlah elemen tidak sesuai! Masukkan lagi.")
        row = input_baris(f"Baris {i+1}: ")
    A.append(row)

print("\nMatriks A:")
for r in A:
    print(r)

# Determinan
detA = determinan(A)
print("\nDeterminannya:", detA)

# Invers
try:
    invA = inverse(A)
    print("\nInvers Matriks A:")
    for r in invA:
        print(r)
except ValueError as e:
    print("ERROR:", e)
    exit()

# Verifikasi
print("\nVerifikasi: A × A^{-1} = I")
hasil = multiply(A, invA)
for r in hasil:
    print(r)

Masukkan ukuran matriks (contoh: 3 atau 3x3): 3

Masukkan elemen-elemen matriks 3x3:
Baris 1: 2 4 7
Baris 2: 3 8 9
Baris 3: 10 14 2

Matriks A:
[Fraction(2, 1), Fraction(4, 1), Fraction(7, 1)]
[Fraction(3, 1), Fraction(8, 1), Fraction(9, 1)]
[Fraction(10, 1), Fraction(14, 1), Fraction(2, 1)]

Determinannya: -150

Invers Matriks A:
[Fraction(11, 15), Fraction(-3, 5), Fraction(2, 15)]
[Fraction(-14, 25), Fraction(11, 25), Fraction(-1, 50)]
[Fraction(19, 75), Fraction(-2, 25), Fraction(-2, 75)]

Verifikasi: A × A^{-1} = I
[Fraction(1, 1), Fraction(0, 1), Fraction(0, 1)]
[Fraction(0, 1), Fraction(1, 1), Fraction(0, 1)]
[Fraction(0, 1), Fraction(0, 1), Fraction(1, 1)]


In [ ]:
#True




from fractions import Fraction
import re

# =============================
# Format Fraction → string biasa
# =============================
def fmt(x):
    if x.denominator == 1:
        return str(x.numerator)          # contoh: 5
    else:
        return f"{x.numerator}/{x.denominator}"  # contoh: 11/15


def print_matrix(M, title):
    print("\n" + title)
    print("-" * len(title))
    for row in M:
        print([fmt(x) for x in row])


# =============================
# Input baris matrix
# =============================
def input_baris(prompt):
    raw = input(prompt)
    raw = raw.replace(",", ".")
    return [Fraction(x) for x in raw.split()]

# =============================
# Determinan rekursif
# =============================
def determinan(M):
    n = len(M)
    if n == 1:
        return M[0][0]
    if n == 2:
        return M[0][0] * M[1][1] - M[0][1] * M[1][0]

    det = Fraction(0)
    for j in range(n):
        minor = []
        for row in M[1:]:
            minor.append([row[k] for k in range(n) if k != j])
        det += ((-1)**j) * M[0][j] * determinan(minor)
    return det

# =============================
# Minor matrix
# =============================
def minor_matrix(M, i, j):
    return [
        [M[r][c] for c in range(len(M)) if c != j]
        for r in range(len(M)) if r != i
    ]

# =============================
# Cofactor matrix
# =============================
def matrix_cofactor(M):
    n = len(M)
    C = [[Fraction(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            C[i][j] = ((-1)**(i+j)) * determinan(minor_matrix(M, i, j))
    return C

# =============================
# Transpose
# =============================
def transpose(M):
    return [list(row) for row in zip(*M)]

# =============================
# Invers via adjoin
# =============================
def inverse(M):
    detA = determinan(M)
    C = matrix_cofactor(M)
    adj = transpose(C)
    inv = [[adj[i][j] / detA for j in range(len(M))] for i in range(len(M))]
    return detA, C, adj, inv

# =============================
# Matrix multiplication
# =============================
def multiply(A, B):
    n = len(A)
    R = [[Fraction(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                R[i][j] += A[i][k] * B[k][j]
    return R


# =============================
# MAIN PROGRAM
# =============================
ukuran = input("Masukkan ukuran matriks (contoh: 3 atau 3x3): ")
angka = re.findall(r'\d+', ukuran)
n = int(angka[0])

print(f"\nMasukkan elemen-elemen matriks {n}x{n}:")
A = []
for i in range(n):
    row = input_baris(f"Baris {i+1}: ")
    while len(row) != n:
        print("Jumlah elemen tidak sesuai! Masukkan ulang.")
        row = input_baris(f"Baris {i+1}: ")
    A.append(row)

# Tampilkan matriks A
print_matrix(A, "Matriks A")

# Hitung invers & semua komponennya
detA, C, adj, invA = inverse(A)

# Tampilkan determinant
print("\nDeterminant A:")
print("---------------")
print(fmt(detA))

# Tampilkan cofactor
print_matrix(C, "Matriks Cofactor")

# Tampilkan Adjoin
print_matrix(adj, "Matriks Adjoin (Transpose Cofactor)")

# Tampilkan Invers
print_matrix(invA, "Invers Matriks A")

# Verifikasi
verify = multiply(A, invA)
print_matrix(verify, "Verifikasi A × A^(-1) = I")

Masukkan ukuran matriks (contoh: 3 atau 3x3): 3 X 3

Masukkan elemen-elemen matriks 3x3:
Baris 1: 4 5 6
Baris 2: 1 1 6
Baris 3: 0 7 9

Matriks A
---------
['4', '5', '6']
['1', '1', '6']
['0', '7', '9']

Determinant A:
---------------
-135

Matriks Cofactor
----------------
['-33', '-9', '7']
['-3', '36', '-28']
['24', '-18', '-1']

Matriks Adjoin (Transpose Cofactor)
-----------------------------------
['-33', '-3', '24']
['-9', '36', '-18']
['7', '-28', '-1']

Invers Matriks A
----------------
['11/45', '1/45', '-8/45']
['1/15', '-4/15', '2/15']
['-7/135', '28/135', '1/135']

Verifikasi A × A^(-1) = I
-------------------------
['1', '0', '0']
['0', '1', '0']
['0', '0', '1']


In [ ]:
from fractions import Fraction
import re

# =============================
# Format Fraction → string biasa
# =============================
def fmt(x):
    if x.denominator == 1:
        return str(x.numerator)
    else:
        return f"{x.numerator}/{x.denominator}"

def print_matrix(M, title):
    print("\n" + title)
    print("-" * len(title))
    for row in M:
        print([fmt(x) for x in row])


# =============================
# Minor matrix
# =============================
def minor_matrix(M, i, j):
    return [
        [M[r][c] for c in range(len(M)) if c != j]
        for r in range(len(M)) if r != i
    ]


# =============================
# Determinan rekursif + penjelasan minor
# =============================
def determinan(M, level=0, explain=False):
    n = len(M)
    if n == 1:
        return M[0][0]

    if n == 2:
        return M[0][0]*M[1][1] - M[0][1]*M[1][0]

    det = Fraction(0)
    for j in range(n):
        minor = minor_matrix(M, 0, j)
        cofactor_val = ((-1)**j) * M[0][j] * determinan(minor)

        if explain:
            print("\n===============================")
            print(f"Elemen baris 1 kolom {j+1}: a[1,{j+1}] = {fmt(M[0][j])}")
            print("Minor untuk elemen ini:")
            print_matrix(minor, "Minor Matrix")
            print(f"Determinant minor   = {fmt(determinan(minor))}")
            print(f"Cofactor C[1,{j+1}]  = (-1)^{j} × a[1,{j+1}] × det(minor)")
            print(f"                    = {fmt(cofactor_val)}")

        det += cofactor_val

    return det


# =============================
# Cofactor matrix + penjelasan
# =============================
def matrix_cofactor(M):
    n = len(M)
    C = [[Fraction(0) for _ in range(n)] for _ in range(n)]

    print("\n===============================")
    print("Menghitung Cofactor Matrix")
    print("===============================")

    for i in range(n):
        for j in range(n):
            minor = minor_matrix(M, i, j)
            det_minor = determinan(minor)
            C_val = ((-1)**(i+j)) * det_minor

            print(f"\nCofactor C[{i+1},{j+1}]")
            print("---------------------")
            print_matrix(minor, "Minor Matrix M{i}{j}")
            print(f"det(minor)     = {fmt(det_minor)}")
            print(f"C[{i+1},{j+1}] = (-1)^({i}+{j}) × det(minor)")
            print(f"              = {fmt(C_val)}")

            C[i][j] = C_val

    return C


# =============================
# Transpose + penjelasan
# =============================
def transpose_with_explain(M):
    print("\n===============================")
    print("Membentuk Adjoin = Transpose Cofactor Matrix")
    print("===============================")

    print_matrix(M, "Cofactor Matrix (C)")

    T = [list(row) for row in zip(*M)]

    print_matrix(T, "Transpose Cofactor = Adjoin")

    return T


# =============================
# Invers via adjoin
# =============================
def inverse_with_explain(M):
    detA = determinan(M, explain=True)
    print("\nDeterminant A = ", fmt(detA))

    C = matrix_cofactor(M)
    adj = transpose_with_explain(C)
    inv = [[adj[i][j] / detA for j in range(len(M))] for i in range(len(M))]

    return detA, C, adj, inv


# =============================
# Matrix multiplication
# =============================
def multiply(A, B):
    n = len(A)
    R = [[Fraction(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                R[i][j] += A[i][k] * B[k][j]
    return R


# =============================
# MAIN PROGRAM
# =============================
ukuran = input("Masukkan ukuran matriks (contoh: 3 atau 3x3): ")
angka = re.findall(r'\d+', ukuran)
n = int(angka[0])

print(f"\nMasukkan elemen-elemen matriks {n}x{n}:")
A = []
for i in range(n):
    raw = input(f"Baris {i+1}: ").replace(",", ".")
    row = [Fraction(x) for x in raw.split()]
    A.append(row)

print_matrix(A, "\nMatriks A")

# Hitung invers + penjelasan lengkap
detA, C, adj, invA = inverse_with_explain(A)

print_matrix(C, "Cofactor Matrix (C)")
print_matrix(adj, "Adjoin Matrix")
print_matrix(invA, "Invers Matriks A")

# Verifikasi
I = multiply(A, invA)
print_matrix(I, "Verifikasi A × A^(-1) = I")

Masukkan ukuran matriks (contoh: 3 atau 3x3): 2

Masukkan elemen-elemen matriks 2x2:
Baris 1: 2 5
Baris 2: 5 7


Matriks A
----------
['2', '5']
['5', '7']

Determinant A =  -11

Menghitung Cofactor Matrix

Cofactor C[1,1]
---------------------

Minor Matrix M{i}{j}
--------------------
['7']
det(minor)     = 7
C[1,1] = (-1)^(0+0) × det(minor)
              = 7

Cofactor C[1,2]
---------------------

Minor Matrix M{i}{j}
--------------------
['5']
det(minor)     = 5
C[1,2] = (-1)^(0+1) × det(minor)
              = -5

Cofactor C[2,1]
---------------------

Minor Matrix M{i}{j}
--------------------
['5']
det(minor)     = 5
C[2,1] = (-1)^(1+0) × det(minor)
              = -5

Cofactor C[2,2]
---------------------

Minor Matrix M{i}{j}
--------------------
['2']
det(minor)     = 2
C[2,2] = (-1)^(1+1) × det(minor)
              = 2

Membentuk Adjoin = Transpose Cofactor Matrix

Cofactor Matrix (C)
-------------------
['7', '-5']
['-5', '2']

Transpose Cofactor = Adjoin
--------------------

In [ ]:
from fractions import Fraction
import pandas as pd
import re

# ===========================
# 1. Fungsi bantu membaca input Fraction
# ===========================
def parse_fraction(x):
    x = x.strip().replace(",", ".")   # support user input 2,5 -> 2.5
    if "/" in x:
        a, b = x.split("/")
        return Fraction(float(a), float(b))
    else:
        return Fraction(float(x))

# ===========================
# 2. Input Ukuran Matriks
# ===========================
ukuran = input("Masukkan ukuran matriks (contoh: 3 atau 3x3): ")
angka = re.findall(r'\d+', ukuran)
n = int(angka[0])

print(f"\nMasukkan elemen-elemen matriks {n}x{n} (pisahkan dengan spasi):")

# ===========================
# 3. Input Matriks
# ===========================
A = []
for i in range(n):
    row_input = input(f"Baris {i+1}: ").split()
    row = [parse_fraction(x) for x in row_input]
    A.append(row)

# ===========================
# 4. Fungsi Hitung Determinan
# ===========================
def determinant(matrix):
    size = len(matrix)
    if size == 1:
        return matrix[0][0]

    det = Fraction(0, 1)

    for col in range(size):
        sub = [row[:col] + row[col+1:] for row in matrix[1:]]
        det += ((-1) ** col) * matrix[0][col] * determinant(sub)

    return det

# ===========================
# 5. Cofactor Matrix
# ===========================
def cofactor_matrix(matrix):
    n = len(matrix)
    C = [[Fraction(0, 1) for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
            sub = [row[:j] + row[j+1:] for k, row in enumerate(matrix) if k != i]
            C[i][j] = ((-1) ** (i+j)) * determinant(sub)
    return C

# ===========================
# 6. Adjoint = Transpose Cofactor
# ===========================
def adjoint(matrix):
    C = cofactor_matrix(matrix)
    n = len(matrix)
    Adj = [[C[j][i] for j in range(n)] for i in range(n)]
    return Adj

# ===========================
# 7. Inverse Matriks
# ===========================
def inverse_matrix(matrix):
    detA = determinant(matrix)
    if detA == 0:
        raise ValueError("Matriks tidak memiliki invers (det = 0).")

    Adj = adjoint(matrix)
    inv = [[Adj[i][j] / detA for j in range(n)] for i in range(n)]
    return inv

# ===========================
# 8. Konversi Fraction -> string (a/b)
# ===========================
def clean(df):
    return df.applymap(
        lambda x: str(int(x)) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"
    )

# ===========================
# 9. Hitung semua
# ===========================
detA = determinant(A)
cofA = cofactor_matrix(A)
adjA = adjoint(A)
invA = inverse_matrix(A)

# ===========================
# 10. Tampilkan Tabel-tabel
# ===========================
df_A = clean(pd.DataFrame(A))
df_cof = clean(pd.DataFrame(cofA))
df_adj = clean(pd.DataFrame(adjA))
df_inv = clean(pd.DataFrame(invA))

print("\n===== Matriks A =====")
display(df_A)

print("\n===== Matriks Cofactor =====")
display(df_cof)

print("\n===== Matriks Adjoint =====")
display(df_adj)

print("\n===== Determinan A =====")
print(detA)

print("\n===== Matriks Invers A =====")
display(df_inv)

# ===========================
# 11. Verifikasi A * A^-1 = I
# ===========================
def multiply(A, B):
    n = len(A)
    result = [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
    return result

verify = multiply(A, invA)
df_verify = clean(pd.DataFrame(verify))

print("\n===== Verifikasi: A * A^-1 =====")
display(df_verify)

Masukkan ukuran matriks (contoh: 3 atau 3x3): 2

Masukkan elemen-elemen matriks 2x2 (pisahkan dengan spasi):
Baris 1: 8 7
Baris 2: 2 4

===== Matriks A =====


/tmp/ipython-input-956765802.py:88: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(


0  1
0  8  7
1  2  4


===== Matriks Cofactor =====


0   1
0   4  -2
1  -7   8


===== Matriks Adjoint =====


0   1
0   4  -7
1  -2   8


===== Determinan A =====
18

===== Matriks Invers A =====


0      1
0   2/9  -7/18
1  -1/9    4/9


===== Verifikasi: A * A^-1 =====


/tmp/ipython-input-956765802.py:88: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(


0  1
0  1  0
1  0  1

In [ ]:
from sympy import Matrix, Rational
import pandas as pd

# === Input ukuran matriks ===
n = int(input("Masukkan ordo matriks (contoh: 2, 3, 4,...): "))

print(f"Masukkan elemen matriks {n}x{n} (boleh pecahan contoh: 1/2, 3/4):")

data = []
for i in range(n):
    row = input(f"Baris {i+1}: ").split()
    data.append([Rational(x) for x in row])

# Buat matriks SymPy agar tetap rasional
A = Matrix(data)

# Perhitungan
determinant = A.det()
cofactor_mat = A.cofactor_matrix()
adjoint_mat = A.adjugate()

# Cek inverse
inverse_mat = None
if determinant != 0:
    inverse_mat = A.inv()

# Fungsi styling dataframe
def style(df):
    return df.style.background_gradient(cmap="coolwarm")

# Tampilan hasil
print("\n=== Matriks Input ===")
display(style(pd.DataFrame(A.tolist())))

print("\n=== Determinan Matriks ===")
print(determinant)

print("\n=== Matriks Cofactor ===")
display(style(pd.DataFrame(cofactor_mat.tolist())))

print("\n=== Matriks Adjoint ===")
display(style(pd.DataFrame(adjoint_mat.tolist())))

if inverse_mat:
    print("\n=== Matriks Invers ===")
    display(style(pd.DataFrame(inverse_mat.tolist())))
else:
    print("\n⚠ Matriks tidak memiliki invers karena determinan = 0")

Masukkan ordo matriks (contoh: 2, 3, 4,...): 2
Masukkan elemen matriks 2x2 (boleh pecahan contoh: 1/2, 3/4):
Baris 1: 2 4
Baris 2: 8 7

=== Matriks Input ===



=== Determinan Matriks ===
-18

=== Matriks Cofactor ===



=== Matriks Adjoint ===



=== Matriks Invers ===


In [9]:

# ======================
#   MATRIX HACKER MODE
# ======================

from sympy import Matrix, Rational
import pandas as pd
import random, time, sys

# ------------ Hacker Opening Animation -------------
def typewrite(text, delay=(0.01, 0.04)):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(random.uniform(delay[0], delay[1]))
    print()

ascii_banner = r"""
#    ███████╗    ███╗   ███╗ █████╗ ████████╗██████╗ ██╗██╗  ██╗
#    ██╔════╝    ████╗ ████║██╔══██╗╚══██╔══╝██╔══██╗██║╚██╗██╔╝
#    █████╗█████╗██╔████╔██║███████║   ██║   ██████╔╝██║ ╚███╔╝
#    ██╔══╝╚════╝██║╚██╔╝██║██╔══██║   ██║   ██╔══██╗██║ ██╔██╗
#    ███████╗    ██║ ╚═╝ ██║██║  ██║   ██║   ██║  ██║██║██╔╝ ██╗
#    ╚══════╝    ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝
#
"""

print("\033[92m")  # green terminal color
typewrite(ascii_banner, delay=(0.001,0.003))
typewrite(">> ACCESS GRANTED", delay=(0.02,0.07))
typewrite(">> BOOTING MATRIX ANALYZER...", delay=(0.02,0.07))
typewrite(">> READY.\n", delay=(0.02,0.06))


# ---------------- Input ----------------

n = int(input(">> Enter matrix size (e.g., 2, 3, 4): "))

print(f"\n>> Input matrix values ({n}x{n}). Fractions allowed (e.g. 1/2, 3/4):\n")

data = []
for i in range(n):
    row = input(f"Row {i+1}: ").split()
    data.append([Rational(x) for x in row])

A = Matrix(data)

# ---------------- Calculations ----------------
determinant = A.det()
cofactor_mat = A.cofactor_matrix()
adjoint_mat = A.adjugate()

inverse_mat = None
if determinant != 0:
    inverse_mat = A.inv()


# ---------------- Styling (HACKER MODE) ----------------
def hacker_mode(df):
    return (
        df.style
        .applymap(lambda _: "background-color: black; color: #00FF41; font-family:'Courier New'; font-size:20px;")
        .set_properties(**{
            "border": "1px solid #00FF41",
            "text-align": "center",
        })
    )


# ---------------- Output ----------------

typewrite("\n>> MATRIX DETECTED:", delay=(0.005,0.02))
display(hacker_mode(pd.DataFrame(A.tolist())))

typewrite(f"\n>> DETERMINANT = {determinant}", delay=(0.01,0.05))

typewrite("\n>> COFACTOR MATRIX:", delay=(0.01,0.05))
display(hacker_mode(pd.DataFrame(cofactor_mat.tolist())))

typewrite("\n>> ADJOINT MATRIX:", delay=(0.01,0.05))
display(hacker_mode(pd.DataFrame(adjoint_mat.tolist())))

if inverse_mat:
    typewrite("\n>> INVERSE MATRIX:", delay=(0.01,0.05))
    display(hacker_mode(pd.DataFrame(inverse_mat.tolist())))
else:
    typewrite("\n>> WARNING: MATRIX HAS NO INVERSE (det = 0)", delay=(0.01,0.05))


print("\n> SESSION COMPLETE.\nSYSTEM STABLE.\n🟢")




#    ███████╗    ███╗   ███╗ █████╗ ████████╗██████╗ ██╗██╗  ██╗
#    ██╔════╝    ████╗ ████║██╔══██╗╚══██╔══╝██╔══██╗██║╚██╗██╔╝
#    █████╗█████╗██╔████╔██║███████║   ██║   ██████╔╝██║ ╚███╔╝
#    ██╔══╝╚════╝██║╚██╔╝██║██╔══██║   ██║   ██╔══██╗██║ ██╔██╗
#    ███████╗    ██║ ╚═╝ ██║██║  ██║   ██║   ██║  ██║██║██╔╝ ██╗
#    ╚══════╝    ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝
#

>> ACCESS GRANTED
>> BOOTING MATRIX ANALYZER...
>> READY.

>> Enter matrix size (e.g., 2, 3, 4): 3

>> Input matrix values (3x3). Fractions allowed (e.g. 1/2, 3/4):

Row 1: 2 -1 3
Row 2: 0 4 5
Row 3: 1 -2 0

>> MATRIX DETECTED:


/tmp/ipython-input-1482595953.py:61: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(lambda _: "background-color: black; color: #00FF41; font-family:'Courier New'; font-size:20px;")



>> DETERMINANT = 3

>> COFACTOR MATRIX:



>> ADJOINT MATRIX:



>> INVERSE MATRIX:



> SESSION COMPLETE.
SYSTEM STABLE.
🟢


In [ ]:
from fractions import Fraction

# ===========================
# Functions from other cells, adapted for Fraction and eval(x) input
# ===========================

def minor_matrix(M, i, j):
    # Ensure M[0] exists to get column count, important for non-empty matrices
    if not M or not M[0]:
        raise ValueError("Cannot calculate minor of an empty or malformed matrix.")
    return [
        [M[r][c] for c in range(len(M[0])) if c != j] # Iterate columns based on first row's length
        for r in range(len(M)) if r != i
    ]

def determinant(M):
    n = len(M)
    if n == 0: # Handle empty matrix
        return Fraction(0)
    if n != len(M[0]): # Ensure it's a square matrix for determinant
        raise ValueError("Matrix must be square to calculate determinant.")

    if n == 1:
        return M[0][0]

    det = Fraction(0)
    for j in range(n):
        minor = minor_matrix(M, 0, j)
        det += ((-1)**j) * M[0][j] * determinant(minor)
    return det

def cofactor_matrix(M):
    n = len(M)
    if n == 0 or n != len(M[0]): # Ensure it's a square matrix for cofactor
        raise ValueError("Matrix must be square to calculate cofactor matrix.")
    C = [[Fraction(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            minor = minor_matrix(M, i, j)
            C[i][j] = ((-1)**(i+j)) * determinant(minor)
    return C

def transpose(M):
    if not M: return [] # Handle empty matrix
    return [list(row) for row in zip(*M)]

def adjoint(M):
    C = cofactor_matrix(M)
    return transpose(C)

def inverse(M):
    detA = determinant(M)
    if detA == 0:
        return None # Matrix does not have an inverse

    adj = adjoint(M)
    inv = [[adj[i][j] / detA for j in range(len(M))] for i in range(len(M))]
    return inv


def run():
    while True:
        try:
            n = int(input("Matrix size: "))
            if n <= 0:
                print("Matrix size must be a positive integer.")
                continue
            break
        except ValueError:
            print("Invalid input. Please enter an integer for matrix size.")

    print(f"Input matrix (enter {n} elements per row, separated by spaces. Example for a {n}x{n} matrix row: '1/2 3/4'):")
    matrix = []

    for i in range(n):
        while True: # Loop until valid input for the current row is received
            row_input_str = input(f"Row {i+1}: ")
            row_elements_str = row_input_str.split()
            if len(row_elements_str) == n:
                try:
                    current_row = []
                    for x_str in row_elements_str:
                        # Handle integers, floats, and fractions robustly
                        if '/' in x_str:
                            current_row.append(Fraction(x_str))
                        elif '.' in x_str:
                            current_row.append(Fraction(float(x_str)))
                        else:
                            current_row.append(Fraction(int(x_str))) # Convert int to Fraction
                    matrix.append(current_row)
                    break # Exit inner while loop, row is valid
                except (ValueError, ZeroDivisionError) as e:
                    print(f"Invalid input in Row {i+1}: {e}. Please enter valid numbers or fractions.")
            else:
                print(f"Incorrect number of elements. Please enter exactly {n} elements for Row {i+1}.")

    print("\nMatrix:", matrix)
    try:
        det = determinant(matrix)
        print("\nDeterminant:", det)

        cof = cofactor_matrix(matrix)
        print("\nCofactor:", cof)

        adj = adjoint(matrix)
        print("\nAdjoint:", adj)

        inv = inverse(matrix)
        print("\nInverse:", inv if inv else "No inverse (det=0)")
    except ValueError as e:
        print(f"\nError during matrix operations: {e}")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")


run()